"""Pydantic Schemas and Domain Types for Credit Risk and NPA Classification.

Enforces strict type validation and boundary checks for portfolio accounts.
"""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field, field_validator


class AssetClassification(str, Enum):
    """RBI IRAC Asset Classification Categories for NBFC-ND-SI."""
    STANDARD = "STANDARD"
    SMA_0 = "SMA_0"
    SMA_1 = "SMA_1"
    SMA_2 = "SMA_2"
    SUB_STANDARD = "SUB_STANDARD"
    DOUBTFUL_1 = "DOUBTFUL_1"
    DOUBTFUL_2 = "DOUBTFUL_2"
    DOUBTFUL_3 = "DOUBTFUL_3"
    LOSS = "LOSS"


class ProductType(str, Enum):
    """Core lending product portfolios offered by Vridhi Financial Services."""
    SME_LENDING = "SME_LENDING"
    VEHICLE_FINANCE = "VEHICLE_FINANCE"
    GOLD_LOAN = "GOLD_LOAN"
    MICROFINANCE = "MICROFINANCE"
    HOUSING_FINANCE = "HOUSING_FINANCE"


class LoanAccount(BaseModel):
    """Input representation of a loan account from Core Banking (FinnOne DS-01)."""
    account_id: str = Field(..., description="Unique account identifier")
    customer_id: str = Field(..., description="Unique customer master ID")
    customer_name: str = Field(..., max_length=150)
    product_type: ProductType
    sanctioned_amount: float = Field(..., gt=0)
    outstanding_principal: float = Field(..., ge=0)
    current_dpd: int = Field(..., ge=0, description="Days Past Due counter")
    secured_percentage: float = Field(default=1.0, ge=0.0, le=1.0)
    cibil_score: int = Field(..., ge=-1, le=900, description="-1 indicates no-hit")
    annual_income: float = Field(default=0.0, ge=0.0)
    monthly_emi: float = Field(default=0.0, ge=0.0)

    @field_validator("outstanding_principal")
    @classmethod
    def validate_outstanding(cls, v: float, info) -> float:
        sanctioned = info.data.get("sanctioned_amount")
        if sanctioned is not None and v > sanctioned * 1.5:
            raise ValueError("Outstanding balance exceeds maximum permissible credit ceiling")
        return v


class CreditAssessmentResult(BaseModel):
    """Output evaluation generated by the Credit Risk Engine."""
    account_id: str
    product_type: ProductType
    cibil_score: int
    cibil_decision: str
    requires_override: bool
    scorecard_points: int
    probability_of_default: float
    loss_given_default: float
    exposure_at_default: float
    expected_credit_loss: float
    asset_classification: AssetClassification
    is_npa: bool
    provision_percentage: float
    required_provision_amount: float
    crilc_reportable: bool
